# Generated by Django 4.1.3 on 2022-12-30 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_alter_userprofile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='social_network/profile_picture'),
        ),
    ]
