# Generated by Django 4.1.3 on 2022-12-27 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_userprofile_user'),
        ('posts', '0003_post_location_alter_comment_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='like',
            field=models.ManyToManyField(blank=True, to='accounts.userprofile'),
        ),
    ]
