# Generated by Django 4.1.3 on 2022-12-30 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_alter_comment_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(max_length=255, upload_to='social_network/posts'),
        ),
    ]
