# Generated by Django 4.1.3 on 2023-01-02 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_collection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='post',
            field=models.ManyToManyField(blank=True, to='posts.post'),
        ),
    ]
