# Generated by Django 4.1.3 on 2023-01-02 13:54

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_alter_comment_user_collection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, max_length=100, populate_from='name', unique=True),
        ),
    ]
