# Generated by Django 4.1.3 on 2023-01-02 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_alter_collection_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collection',
            old_name='post',
            new_name='posts',
        ),
    ]
