# Generated by Django 4.1.3 on 2023-01-03 17:41

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0010_rename_post_collection_posts'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='collection',
            unique_together={('user', 'slug')},
        ),
    ]
