# Generated by Django 4.1.3 on 2023-01-12 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_collection_collaborators'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='cover_url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
