# Generated by Django 4.1.3 on 2023-01-10 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notification_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('comment', 'comment'), ('save', 'save'), ('reply', 'reply'), ('like', 'like'), ('follow', 'follow')], max_length=20),
        ),
    ]
