# Generated by Django 4.1.3 on 2023-01-11 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('comment', 'comment'), ('save', 'save'), ('reply', 'reply'), ('like', 'like'), ('follow', 'follow'), ('invite', 'invite')], max_length=20),
        ),
    ]
